### ISSUE TITLE
How to understand the meaning of only_add_one_perturbation and leave_one_out_perturbation?

### ISSUE THREAD

**Issue by HeBangYan** [xherdan76/A-Unified-Approach-to-Interpreting-and-Boosting-Adversarial-Transferability#1]
What does `only_add_one_perturbation and leave_one_out_perturbation` mean in the sample_for_interaction function (in the codes/basic_functions/ouradvertorch/attacks/interaction_loss.py file)?

Thanks for your answer. 🙏

**Comment by 0SillyMonkey0** [comment]
Hi,

The variable `only_add_one_perturbation` represents ${i}$ in the paper, which means only one grid (i) is perturbed;
the variable ` leave_one_out_perturbation` represents $\Omega\setminus {i}$, which means all grids expect (i) are perturbed
