### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by LinQinLiang** [xherdan76/A-Unified-Approach-to-Interpreting-and-Boosting-Adversarial-Transferability#3]
Hello! Here the shape of delta and shape of only_add_one_mask may be different? I get a error here! Shape of X is [16, 3, 224, 224], delta is [16, 3, 224, 224], but the shape of only_add_one_mask is [16*times, 3, 224, 224]

**Comment by LinQinLiang** [comment]
![Uploading 22ff00cffcc6780a9ba795e82f3621b.png…]()

**Comment by LinQinLiang** [comment]
![22ff00cffcc6780a9ba795e82f3621b](https://user-images.githubusercontent.com/45589968/166858402-ed5e3bd3-6496-4d98-a17e-3ef010fb6a48.png)

**Comment by 0SillyMonkey0** [comment]
The current code requires the shape of X and delta to be [1, 3, 224, 224], so the only_add_one_mask ( [times, 3, 224, 224]) can be broadcast to fit the shape of X and delta.
