### ISSUE TITLE
Question about only_add_one_mask

### ISSUE THREAD

**Issue by GolferChen** [xherdan76/A-Unified-Approach-to-Interpreting-and-Boosting-Adversarial-Transferability#4]
Hi, thanks a lot for your great work and the open-source code. 

I have the following problem. Appreciate if you can help:

According to my understanding, ```only_add_one_mask``` should only have one grid being set to ```1```. However, in the following code:

```
only_add_one_mask = torch.zeros_like(delta).repeat(times, 1, 1, 1)
for i in range(times):
    grids = samples[i]
    for grid in grids:
        only_add_one_mask[i:i + 1, :, grid[0], grid[1]] = 1
```
the second for loop will full multiple (```sample_grid_num``` in the code) grids into ```1```.  

Did I understand something wrong? Thanks a lot.

**Comment by GolferChen** [comment]
In my understanding, you sample ```times``` times to approximate the expectation of Eq(4). Did I understand wrong?

**Comment by 0SillyMonkey0** [comment]
Thank you for your interest in our paper. Your understanding is accurate; the mentioned code indeed approximates Eq(4). However, to further mitigate computational costs, we employed a sampling approach. For a more detailed explanation, please refer to Appendix L in https://arxiv.org/pdf/2010.04055.pdf.
